AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3TfRemoteState:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: tf-vault-elixir-remote-state
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
  TfRemoteStateGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: TfRemoteStateGroup
  S3TfRemoteStatePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: TerraformRemoteState
      Groups:
        - !Ref TfRemoteStateGroup
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt S3TfRemoteState.Arn
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub 
              - '${Arn}/vault/terraform.tfstate'
              - { Arn: !GetAtt S3TfRemoteState.Arn }
